name: ekf_legged_robot_env
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- pip
- python
- numpy
- cuda-nvcc 
- ros-humble-desktop
- ros-humble-rmw-cyclonedds-cpp
- ros-humble-rosidl-generator-dds-idl
- ros-humble-plotjuggler-ros
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
# - colcon-notification
- catkin_tools 
- rosdep
- tqdm
- gymnasium
- pip:
  - readchar
  - onnxruntime
  - torch
  - warp-lang
  - mujoco-warp